name: 04-events

on:
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  inspect:
    runs-on: ubuntu-24.04
    steps:
      - name: Show event
        run: |
          echo "Event ${{ toJson(github.event) }}"
          echo "Action: ${{ github.event.action }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
