name: 05-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: info-project
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: preparar npm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: install dependencies
        run: |
          echo "Instalando dependencias de info-project"
          pnpm install --frozen-lockfile
          echo "Dependencias instaladas correctamente"

      - name: lint
        run: |
          echo "Ejecutando lint"
          pnpm lint
          echo "Lint ejecutado correctamente"

      - name: Test
        run: |
          echo "Ejecutando tests"
          pnpm test
          echo "Tests ejecutados correctamente"

      - name: Build
        run: |
          pnpm build
